apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "akshackcluster-18c3"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "akshackcluster-18c3"
    spec:
      containers:
        - name: "akshackcluster-18c3"
          image: "monokubeacr.azurecr.io/akshackcluster"
          ports:
          - containerPort: 3009