apiVersion: v1
kind: Service
metadata:
    name: "akshackcluster-18c3"
    labels:
        app: "akshackcluster-18c3"
spec:
    type: ClusterIP
    ports:
    - port: 3009
      targetPort: 3009
      protocol: TCP
      name: http
    selector:
        app: "akshackcluster-18c3"